version: "3"
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/database/data:/var/lib/postgresql/data
      - ./data/database/bkp:/bkp
    env_file:
      - .env